-- * 계정 생성 * --
CREATE USER C##MINIPKKH IDENTIFIED BY MINI;
GRANT CONNECT, RESOURCE TO C##MINIPKKH;
ALTER USER C##MINIPKKH DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


-- * 테이블 생성 * --
CREATE TABLE APP_USER (
USER_ID VARCHAR2(12) PRIMARY KEY,
USER_PWD VARCHAR2(12) NOT NULL,
USER_NAME VARCHAR2(18) NOT NULL,
USER_AGE NUMBER DEFAULT 0 CHECK (USER_AGE >= 0) NOT NULL,
USER_BALANCE NUMBER DEFAULT 0 CHECK (USER_BALANCE >=0) NOT NULL
);

CREATE TABLE CONTENT (
CONTENT_ID VARCHAR2(30) PRIMARY KEY,
CONTENT_TITLE VARCHAR2(100) CONSTRAINT UQ_TT UNIQUE NOT NULL,
CONTENT_PRICE NUMBER DEFAULT 0 CHECK (CONTENT_PRICE >= 0) NOT NULL,
CONTENT_AGE_LIMIT NUMBER DEFAULT 19 CHECK (CONTENT_AGE_LIMIT >= 0) NOT NULL,
CONTENT_UPLOAD_DATE DATE NOT NULL
);

CREATE TABLE ENTERTAINMENT (
CONTENT_ID VARCHAR2(30) PRIMARY KEY REFERENCES CONTENT(CONTENT_ID),
CONTENT_ENTERTAINERS VARCHAR2(100)
);

CREATE TABLE MOVIE(
CONTENT_ID VARCHAR2(30) PRIMARY KEY REFERENCES CONTENT(CONTENT_ID),
CONTENT_RATING NUMBER CHECK (CONTENT_RATING >=1 AND CONTENT_RATING <= 5)
);

CREATE TABLE DOCUMENTARY(
CONTENT_ID VARCHAR2(30) PRIMARY KEY REFERENCES CONTENT(CONTENT_ID),
CONTENT_GENRE VARCHAR2(20)
);

-- * 데이터 추가 * --
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('10001', '알던 형님', 1500, 15, TO_DATE('2006-04-23', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('10002', '놀면 뭐혀', 1000, 12 ,TO_DATE('2006-04-21', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('10003', '냉장고를 맡겨줘', 2000, 9, TO_DATE('2006-04-20', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('10004', '지구 오락관', 2000, 15, TO_DATE('2006-04-26', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('10005', '무박 2일', 2000, 12, TO_DATE('2006-04-28', 'YYYY-MM-DD'));

INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('20001', '009 Secret Mission', 11000, 15, TO_DATE('2006-04-18', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('20002', 'Mission Is Passable', 10000, 18, TO_DATE('2006-04-22', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('20003', '드라큘라와 무한섬', 12000, 19, TO_DATE('2006-04-20', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('20004', '반지 전쟁', 14000, 9, TO_DATE('2006-03-20', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('20005', '동물원 이야기', 9000, 12, TO_DATE('2006-05-20', 'YYYY-MM-DD'));

INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('30001', '침팬지의 일생', 1200, 12, TO_DATE('2006-04-20', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('30002', '벌거벗은 역사', 3000, 15, TO_DATE('2006-04-22', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('30003', '우주의 비밀', 700, 9, TO_DATE('2006-04-26', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('30004', '새의 습성', 500, 9, TO_DATE('2006-04-29', 'YYYY-MM-DD'));
INSERT INTO CONTENT(CONTENT_ID, CONTENT_TITLE, CONTENT_PRICE, CONTENT_AGE_LIMIT, CONTENT_UPLOAD_DATE) VALUES ('30005', '중세 병기의 이해', 1500, 18, TO_DATE('2006-04-15', 'YYYY-MM-DD'));

INSERT INTO ENTERTAINMENT (CONTENT_ID, CONTENT_ENTERTAINERS) VALUES ('10001', '유호동, 서수근, 이장훈');
INSERT INTO ENTERTAINMENT (CONTENT_ID, CONTENT_ENTERTAINERS) VALUES ('10002', '강재석, 허우재, 주경환');
INSERT INTO ENTERTAINMENT (CONTENT_ID, CONTENT_ENTERTAINERS) VALUES ('10003', '최성주, 김정환, 안현석');
INSERT INTO ENTERTAINMENT (CONTENT_ID, CONTENT_ENTERTAINERS) VALUES ('10004', '이유진, 안은지, 이미');
INSERT INTO ENTERTAINMENT (CONTENT_ID, CONTENT_ENTERTAINERS) VALUES ('10005', '유호동, 서수근, 지승기');

INSERT INTO MOVIE (CONTENT_ID, CONTENT_RATING) VALUES ('20001', 4.1);
INSERT INTO MOVIE (CONTENT_ID, CONTENT_RATING) VALUES ('20002', 4.4);
INSERT INTO MOVIE (CONTENT_ID, CONTENT_RATING) VALUES ('20003', 4.8);
INSERT INTO MOVIE (CONTENT_ID, CONTENT_RATING) VALUES ('20004', 4.3);
INSERT INTO MOVIE (CONTENT_ID, CONTENT_RATING) VALUES ('20005', 4.2);

INSERT INTO DOCUMENTARY (CONTENT_ID, CONTENT_GENRE) VALUES ('30001', '동물');
INSERT INTO DOCUMENTARY (CONTENT_ID, CONTENT_GENRE) VALUES ('30002', '인문학');
INSERT INTO DOCUMENTARY (CONTENT_ID, CONTENT_GENRE) VALUES ('30003', '과학');
INSERT INTO DOCUMENTARY (CONTENT_ID, CONTENT_GENRE) VALUES ('30004', '동물');
INSERT INTO DOCUMENTARY (CONTENT_ID, CONTENT_GENRE) VALUES ('30005', '인문학');

INSERT INTO APP_USER (USER_ID, USER_PWD, USER_NAME, USER_AGE, USER_BALANCE) VALUES ('kkh2007', '1111', '권경환', 20, 30000);
INSERT INTO APP_USER (USER_ID, USER_PWD, USER_NAME, USER_AGE, USER_BALANCE) VALUES ('child09', '1111', '어린이', 9, 3000);
INSERT INTO APP_USER (USER_ID, USER_PWD, USER_NAME, USER_AGE, USER_BALANCE) VALUES ('child15', '1111', '중학생', 15, 10000);
INSERT INTO APP_USER (USER_ID, USER_PWD, USER_NAME, USER_AGE, USER_BALANCE) VALUES ('child18', '1111', '고교생', 18, 20000);

COMMIT;